name: kailo_dashboards
channels:
  - conda-forge
dependencies:
  - folium=0.14.0
  - geopandas=0.9.0
  - jupyterlab=3.6.3
  - jupyterlab-spellchecker=0.7.2
  - matplotlib=3.8.0
  - numpy=1.26.0
  - pandas=2.1.1
  - pip=23.3
  - plotly=5.9.0
  - python=3.10.6
  - pip:
    - streamlit==1.28.2
    - flake8==6.0.0
    - pycodestyle_magic==0.5
    - mypy==1.1.1
    - nbqa==1.6.4
    - statsmodels==0.14.0
    - odfpy==1.4.1